---
title: "Assignment 03"
author: "Amyre"
date: "2025-01-20"
output: html_document
---

# Group Members

Amyre Wells 20320047
Mackenzie Calhoun 20265644
Autumn Hodgins 20270064
Kyle Samson (20294258)
Matteo Ienzi (20270101)


Part 1
1
Load Packages
Load Data

```{r}
Data=read.csv("https://colauttilab.github.io/Data/ColauttiBarrett2013Data.csv",header=T)
library(ggplot2)
library(dplyr)
library (tidyr)
library(MASS)
library(klaR)
library(caret)
```

2
Inspect Data
Check Normality 
Report Anomalies
Fix Anomalies

```{r}
head(Data)
tail(Data)
dim(Data)
summary(Data)
str(Data)
any(is.na(Data))


#check for nas
any(is.na(Data))
#removed the NAs and replaced them with thee means 
data_clean <- Data %>%
  mutate(across(where(is.numeric), ~ ifelse(is.na(.), mean(., na.rm = TRUE), .)))
data_clean
```

Check Normality 
```{r}
for (i in names(Data)[8:ncol(Data)]) { #iterate through column names from 8 on
  print(ggplot(Data, aes(x = !!sym(i))) + #plot column name
    geom_histogram())
}
```

## 3
#### Scale Variables

#### Explain Scaling Choice


## 4
#### Feature Selection Explanation

## 5
#### Data Splitting


# Part 2
## 1
#### Run LDAs


## 2
#### LD Axis Explanation


## 3
#### Explore LD object


## 4
#### Obtain LDA Scores

## 5


## 6


## 7